# Generated by Django 5.2.3 on 2025-07-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_tolist_user_id'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totasks',
            name='user_id',
        ),
        migrations.AddField(
            model_name='totasks',
            name='list_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='lists.tolist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totasks',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('noncompleted', 'Non Completed')], max_length=50),
        ),
    ]
