# Generated by Django 5.2.3 on 2025-07-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_tolist_user_id'),
        ('tasks', '0002_remove_totasks_user_id_totasks_list_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totasks',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lists.tolist'),
        ),
    ]
