# Generated by Django 5.2.4 on 2025-07-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_todolist_remove_tolist_user_id'),
        ('tasks', '0003_alter_totasks_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('noncompleted', 'Not Completed')], max_length=50)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lists.todolist')),
            ],
        ),
        migrations.DeleteModel(
            name='ToTasks',
        ),
    ]
