# Generated by Django 5.2.3 on 2025-07-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customeuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='name',
        ),
    ]
