# Generated by Django 5.2.3 on 2025-07-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customeuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
