# Generated by Django 5.2.4 on 2025-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lists', '0005_todolist_user_delete_tolist'),
        ('user', '0009_customuser_delete_customeuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomeUser',
        ),
    ]
