# Generated by Django 5.2.4 on 2025-08-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_todolist_user_delete_tolist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read and Write')], max_length=10)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.todolist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'todo_list')},
            },
        ),
    ]
