# Generated by Django 5.2.4 on 2025-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_alter_todolistpermission_todo_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolistpermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='todolistpermission',
            name='permission_type',
            field=models.CharField(choices=[('0', 'Read Only'), ('1', 'Full Crud')], default='0', max_length=10),
        ),
    ]
