# Generated by Django 5.2.4 on 2025-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_alter_todolistpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistpermission',
            name='permission_type',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Full Crud')], default='read', max_length=10),
        ),
    ]
