# Generated by Django 5.2.4 on 2025-08-03 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_alter_todolistpermission_permission_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolistpermission',
            unique_together={('user', 'todo_list')},
        ),
    ]
